# Form implementation generated from reading ui file 'c:\Users\mprob\Documents\Proyectos\Sistema de Estimacion de Rutas\SER\app\resources\ui\configLoad.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 329)
        Dialog.setStyleSheet("QDialog{\n"
"    background: rgb(184, 255, 183);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(10)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_5)
        self.leAnchTroch = QtWidgets.QLineEdit(parent=self.frame)
        self.leAnchTroch.setObjectName("leAnchTroch")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.leAnchTroch)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_6)
        self.leAnchBanq = QtWidgets.QLineEdit(parent=self.frame)
        self.leAnchBanq.setObjectName("leAnchBanq")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.leAnchBanq)
        self.lePendBanq = QtWidgets.QLineEdit(parent=self.frame)
        self.lePendBanq.setObjectName("lePendBanq")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lePendBanq)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_7)
        self.leDist = QtWidgets.QLineEdit(parent=self.frame)
        self.leDist.setClearButtonEnabled(False)
        self.leDist.setObjectName("leDist")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.leDist)
        self.lePendTalud = QtWidgets.QLineEdit(parent=self.frame)
        self.lePendTalud.setObjectName("lePendTalud")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lePendTalud)
        self.lePendTroch = QtWidgets.QLineEdit(parent=self.frame)
        self.lePendTroch.setObjectName("lePendTroch")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lePendTroch)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ancho de Trocha"))
        self.label_5.setText(_translate("Dialog", "Pendiente transversal\n"
"del Camino"))
        self.leAnchTroch.setPlaceholderText(_translate("Dialog", "distancia [m]"))
        self.label_2.setText(_translate("Dialog", "Ancho de Banquina"))
        self.label_6.setText(_translate("Dialog", "Pendiente transversal\n"
"de Banquina"))
        self.leAnchBanq.setPlaceholderText(_translate("Dialog", "distancia [m]"))
        self.lePendBanq.setPlaceholderText(_translate("Dialog", "ángulo en radianes"))
        self.label_3.setText(_translate("Dialog", "Diastancia al plano\n"
"de referencia"))
        self.label_7.setText(_translate("Dialog", "Pendiente del Talud\n"
"Lateral"))
        self.leDist.setPlaceholderText(_translate("Dialog", "distancia [m]"))
        self.lePendTalud.setPlaceholderText(_translate("Dialog", "ángulo en radianes"))
        self.lePendTroch.setPlaceholderText(_translate("Dialog", "ángulo en radianes"))
